version: '3.8'

services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    expose:
      - "5000"
    networks:
      - appnet

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
